classmates=['huang','ge','gu','gong','ni']
print(len(classmates))
print(classmates[-1],classmates[-2])
classmates.append('guo')
print(len(classmates))
classmates.insert(1,'wu')
print(classmates[1],classmates[2])
classmates.pop(1)
print(classmates[1])
classmates.pop()
print(len(classmates))
classmates[1]='guo'
print(classmates[1])
classmates[1]='ge'
print(classmates[1])
L=['gu',1,classmates]
print(L[2][1])
L=[]
print(len(L))